# Generated by Django 4.1.6 on 2023-02-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='some text', max_length=256),
            preserve_default=False,
        ),
    ]
